# generated by datamodel-codegen:
#   filename:  rule.schema.json
#   timestamp: 2026-06-21T09:09:37+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field, RootModel


class Rule(RootModel[Any]):
    root: Any = Field(..., title='Rule')


class Operator(Enum):
    eq = 'eq'
    neq = 'neq'
    lt = 'lt'
    lte = 'lte'
    gt = 'gt'
    gte = 'gte'
    in_ = 'in'
    not_in = 'not_in'
    contains = 'contains'
    empty = 'empty'
    not_empty = 'not_empty'


class Predicate(BaseModel):
    field: str
    op: Operator
    value: Any | None = None


class Condition(BaseModel):
    all: list[ConditionOrPredicate] | None = None
    any: list[ConditionOrPredicate] | None = None


class DeterministicRule(BaseModel):
    condition: Condition
    action: str


class LLMAssistedRule(BaseModel):
    condition: Condition
    action: str
    requires_human_approval: Literal[True]


class HumanOnlyRule(BaseModel):
    condition: Condition
    action: str


class ConditionOrPredicate(RootModel[Predicate | Condition]):
    root: Predicate | Condition


Condition.model_rebuild()
