# generated by datamodel-codegen:
#   filename:  rule.schema.json
#   timestamp: 2026-08-16T00:09:08+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field, RootModel, conint


class DecisionZone(Enum):
    deterministic = 'deterministic'
    llm_assisted = 'llm_assisted'
    human_only = 'human_only'


class Span(BaseModel):
    start: conint(ge=0) = Field(..., description='Character offset from document start')
    end: conint(ge=0) = Field(..., description='Character offset (exclusive)')


class Citation(BaseModel):
    span: Span
    quoted_text: str = Field(
        ..., description='Verbatim text from source document within span'
    )


class Operator(Enum):
    eq = 'eq'
    neq = 'neq'
    lt = 'lt'
    lte = 'lte'
    gt = 'gt'
    gte = 'gte'
    in_ = 'in'
    not_in = 'not_in'
    contains = 'contains'
    empty = 'empty'
    not_empty = 'not_empty'


class Predicate(BaseModel):
    field: str
    op: Operator
    value: Any | None = None


class Rule(BaseModel):
    id: str
    decision_zone: DecisionZone
    action: str
    condition: dict[str, Any]
    severity: str | None = None
    citation: Citation
    metadata: dict[str, Any] | None = None


class Condition(BaseModel):
    all: list[ConditionOrPredicate] | None = None
    any: list[ConditionOrPredicate] | None = None


class DeterministicRule(BaseModel):
    condition: Condition
    action: str
    citation: Citation


class LLMAssistedRule(BaseModel):
    condition: Condition
    action: str
    requires_human_approval: Literal[True]
    citation: Citation


class HumanOnlyRule(BaseModel):
    condition: Condition
    action: str
    citation: Citation


class ConditionOrPredicate(RootModel[Predicate | Condition]):
    root: Predicate | Condition


Condition.model_rebuild()
