# generated by datamodel-codegen:
#   filename:  simulation_report.schema.json
#   timestamp: 2026-06-21T09:09:37+00:00

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, confloat, conint


class Zone(Enum):
    deterministic = 'deterministic'
    llm_assisted = 'llm_assisted'
    human_only = 'human_only'


class Result(BaseModel):
    ticket_id: UUID
    decision: str
    zone: Zone
    matched_human_decision: bool | None = None
    reasoning: str | None = None


class SimulationReport(BaseModel):
    skill_version_id: UUID
    match_rate: confloat(ge=0.0, le=1.0)
    escalation_accuracy: confloat(ge=0.0, le=1.0)
    contradiction_count: conint(ge=0) | None = None
    automation_candidate_count: conint(ge=0) | None = None
    results: list[Result]
