# generated by datamodel-codegen:
#   filename:  simulation_report.schema.json
#   timestamp: 2026-08-12T19:11:51+00:00

from __future__ import annotations

from enum import Enum
from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field, confloat, conint


class Zone(Enum):
    deterministic = 'deterministic'
    llm_assisted = 'llm_assisted'
    human_only = 'human_only'


class Result(BaseModel):
    ticket_id: UUID
    decision: str
    zone: Zone
    matched_human_decision: bool | None = None
    reasoning: str | None = None


class Citation(BaseModel):
    policy_id: str
    rule_id: str
    span_start: conint(ge=0)
    span_end: conint(ge=0)
    quoted_text: str


class EstimatedFinancialImpact(BaseModel):
    divergent_ticket_count: conint(ge=0) | None = None
    average_refund_amount: float | None = None
    estimated_impact_usd: float | None = None


class Contradiction(BaseModel):
    cluster_key: dict[str, Any] = Field(
        ..., description='Grouping dimensions (amount_band, customer_segment)'
    )
    written_decision: str = Field(..., description='What the extracted skill says')
    observed_decision: str = Field(
        ..., description='What actually happened (ground truth)'
    )
    frequency: confloat(ge=0.0, le=1.0) = Field(
        ..., description='Divergence rate (0-1)'
    )
    ticket_count: conint(ge=0)
    affected_ticket_ids: list[str] | None = None
    citation: Citation | None = None
    estimated_financial_impact: EstimatedFinancialImpact | None = None


class RoiEstimates(BaseModel):
    automation_safe_volume: conint(ge=0) | None = Field(
        None, description='Tickets that can safely be auto-approved'
    )
    manual_review_hours_per_month: float | None = Field(
        None, description='Estimated hours saved by automation'
    )
    estimated_value_usd: float | None = Field(
        None, description='Dollar value of correctly automated decisions'
    )


class SimulationReport(BaseModel):
    skill_version_id: UUID
    match_rate: confloat(ge=0.0, le=1.0)
    escalation_accuracy: confloat(ge=0.0, le=1.0)
    contradiction_count: conint(ge=0) | None = None
    automation_candidate_count: conint(ge=0) | None = None
    results: list[Result]
    contradictions: list[Contradiction] | None = None
    roi_estimates: RoiEstimates | None = None
