# generated by datamodel-codegen:
#   filename:  skill.schema.json
#   timestamp: 2026-08-12T19:08:08+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, conint, constr

from . import rule_schema


class Type(Enum):
    string = 'string'
    number = 'number'
    integer = 'integer'
    boolean = 'boolean'
    array = 'array'


class Input(BaseModel):
    name: str
    type: Type
    description: str | None = None


class DecisionZones(BaseModel):
    deterministic: list[rule_schema.DeterministicRule]
    llm_assisted: list[rule_schema.LLMAssistedRule]
    human_only: list[rule_schema.HumanOnlyRule]


class Skill(BaseModel):
    skill_name: constr(pattern=r'^[a-z_][a-z0-9_]*$')
    owner: str | None = None
    co_owners: list[str] | None = None
    version: conint(ge=1)
    trigger: str
    inputs: list[Input]
    decision_zones: DecisionZones
    audit_requirements: list[str] | None = None
