# generated by datamodel-codegen:
#   filename:  ticket.schema.json
#   timestamp: 2026-08-16T00:09:08+00:00

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel


class Ticket(BaseModel):
    ticket_id: UUID
    refund_amount: float
    purchase_days_ago: int
    customer_segment: str | None = None
    fraud_flags: list[str] | None = None
    refund_reason: str | None = None
    ground_truth_decision: str
