import { z } from "zod";

export const skillSchema = z.object({ "skill_name": z.string().regex(new RegExp("^[a-z_][a-z0-9_]*$")), "owner": z.string().optional(), "co_owners": z.array(z.string()).optional(), "version": z.number().int().gte(1), "trigger": z.string(), "inputs": z.array(z.object({ "name": z.string(), "type": z.enum(["string","number","integer","boolean","array"]), "description": z.string().optional() })), "decision_zones": z.object({ "deterministic": z.array(z.object({ "condition": z.object({ "all": z.array(z.union([z.object({ "field": z.string(), "op": z.enum(["eq","neq","lt","lte","gt","gte","in","not_in","contains","empty","not_empty"]), "value": z.any().optional() }), z.any()])).optional(), "any": z.array(z.union([z.object({ "field": z.string(), "op": z.enum(["eq","neq","lt","lte","gt","gte","in","not_in","contains","empty","not_empty"]), "value": z.any().optional() }), z.any()])).optional() }), "action": z.string() })), "llm_assisted": z.array(z.object({ "condition": z.object({ "all": z.array(z.union([z.object({ "field": z.string(), "op": z.enum(["eq","neq","lt","lte","gt","gte","in","not_in","contains","empty","not_empty"]), "value": z.any().optional() }), z.any()])).optional(), "any": z.array(z.union([z.object({ "field": z.string(), "op": z.enum(["eq","neq","lt","lte","gt","gte","in","not_in","contains","empty","not_empty"]), "value": z.any().optional() }), z.any()])).optional() }), "action": z.string(), "requires_human_approval": z.literal(true) })), "human_only": z.array(z.object({ "condition": z.object({ "all": z.array(z.union([z.object({ "field": z.string(), "op": z.enum(["eq","neq","lt","lte","gt","gte","in","not_in","contains","empty","not_empty"]), "value": z.any().optional() }), z.any()])).optional(), "any": z.array(z.union([z.object({ "field": z.string(), "op": z.enum(["eq","neq","lt","lte","gt","gte","in","not_in","contains","empty","not_empty"]), "value": z.any().optional() }), z.any()])).optional() }), "action": z.string() })) }), "audit_requirements": z.array(z.string()).optional() })

export const ruleSchema = z.any()

export const ticketSchema = z.object({ "ticket_id": z.string().uuid(), "refund_amount": z.number(), "purchase_days_ago": z.number().int(), "customer_segment": z.string().optional(), "fraud_flags": z.array(z.string()).optional(), "refund_reason": z.string().optional(), "ground_truth_decision": z.string() })

export const simulationReportSchema = z.object({ "skill_version_id": z.string().uuid(), "match_rate": z.number().gte(0).lte(1), "escalation_accuracy": z.number().gte(0).lte(1), "contradiction_count": z.number().int().gte(0).optional(), "automation_candidate_count": z.number().int().gte(0).optional(), "results": z.array(z.object({ "ticket_id": z.string().uuid(), "decision": z.string(), "zone": z.enum(["deterministic","llm_assisted","human_only"]), "matched_human_decision": z.boolean().optional(), "reasoning": z.string().optional() })) })

