import { z } from "zod";

export const skillSchema = z.object({ "skill_name": z.string().regex(new RegExp("^[a-z_][a-z0-9_]*$")), "owner": z.string().optional(), "co_owners": z.array(z.string()).optional(), "version": z.number().int().gte(1), "trigger": z.string(), "inputs": z.array(z.object({ "name": z.string(), "type": z.enum(["string","number","integer","boolean","array"]), "description": z.string().optional() })), "decision_zones": z.object({ "deterministic": z.array(z.object({ "condition": z.object({ "all": z.array(z.union([z.object({ "field": z.string(), "op": z.enum(["eq","neq","lt","lte","gt","gte","in","not_in","contains","empty","not_empty"]), "value": z.any().optional() }), z.any()])).optional(), "any": z.array(z.union([z.object({ "field": z.string(), "op": z.enum(["eq","neq","lt","lte","gt","gte","in","not_in","contains","empty","not_empty"]), "value": z.any().optional() }), z.any()])).optional() }), "action": z.string() })), "llm_assisted": z.array(z.object({ "condition": z.object({ "all": z.array(z.union([z.object({ "field": z.string(), "op": z.enum(["eq","neq","lt","lte","gt","gte","in","not_in","contains","empty","not_empty"]), "value": z.any().optional() }), z.any()])).optional(), "any": z.array(z.union([z.object({ "field": z.string(), "op": z.enum(["eq","neq","lt","lte","gt","gte","in","not_in","contains","empty","not_empty"]), "value": z.any().optional() }), z.any()])).optional() }), "action": z.string(), "requires_human_approval": z.literal(true) })), "human_only": z.array(z.object({ "condition": z.object({ "all": z.array(z.union([z.object({ "field": z.string(), "op": z.enum(["eq","neq","lt","lte","gt","gte","in","not_in","contains","empty","not_empty"]), "value": z.any().optional() }), z.any()])).optional(), "any": z.array(z.union([z.object({ "field": z.string(), "op": z.enum(["eq","neq","lt","lte","gt","gte","in","not_in","contains","empty","not_empty"]), "value": z.any().optional() }), z.any()])).optional() }), "action": z.string() })) }), "audit_requirements": z.array(z.string()).optional() })

export const ruleSchema = z.object({ "id": z.string(), "decision_zone": z.enum(["deterministic","llm_assisted","human_only"]), "action": z.string(), "condition": z.record(z.string(), z.any()), "severity": z.string().optional(), "citation": z.object({ "span": z.object({ "start": z.number().int().gte(0).describe("Character offset from document start"), "end": z.number().int().describe("Character offset (exclusive)") }), "quoted_text": z.string().describe("Verbatim text from source document within span") }), "metadata": z.record(z.string(), z.any()).optional() })

export const ticketSchema = z.object({ "ticket_id": z.string().uuid(), "refund_amount": z.number(), "purchase_days_ago": z.number().int(), "customer_segment": z.string().optional(), "fraud_flags": z.array(z.string()).optional(), "refund_reason": z.string().optional(), "ground_truth_decision": z.string() })

export const simulationReportSchema = z.object({ "skill_version_id": z.string().uuid(), "match_rate": z.number().gte(0).lte(1), "escalation_accuracy": z.number().gte(0).lte(1), "contradiction_count": z.number().int().gte(0).optional(), "automation_candidate_count": z.number().int().gte(0).optional(), "results": z.array(z.object({ "ticket_id": z.string().uuid(), "decision": z.string(), "zone": z.enum(["deterministic","llm_assisted","human_only"]), "matched_human_decision": z.boolean().optional(), "reasoning": z.string().optional() })), "contradictions": z.array(z.object({ "cluster_key": z.record(z.string(), z.any()).describe("Grouping dimensions (amount_band, customer_segment)"), "written_decision": z.string().describe("What the extracted skill says"), "observed_decision": z.string().describe("What actually happened (ground truth)"), "frequency": z.number().gte(0).lte(1).describe("Divergence rate (0-1)"), "ticket_count": z.number().int().gte(0), "affected_ticket_ids": z.array(z.string()).optional(), "citation": z.object({ "policy_id": z.string(), "rule_id": z.string(), "span_start": z.number().int().gte(0), "span_end": z.number().int().gte(0), "quoted_text": z.string() }).optional(), "estimated_financial_impact": z.object({ "divergent_ticket_count": z.number().int().gte(0).optional(), "average_refund_amount": z.number().optional(), "estimated_impact_usd": z.number().optional() }).optional() })).optional(), "roi_estimates": z.object({ "automation_safe_volume": z.number().int().gte(0).describe("Tickets that can safely be auto-approved").optional(), "manual_review_hours_per_month": z.number().describe("Estimated hours saved by automation").optional(), "estimated_value_usd": z.number().describe("Dollar value of correctly automated decisions").optional() }).optional() })

